name: Build and Release TemplatePlugin

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17 with caching
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'  # Enable caching for Maven dependencies

    - name: Build with Maven
      run: mvn clean package

    - name: Create GitHub Release and Upload JAR
      run: |
        gh auth login --with-token <<< "${{ secrets.GH_PAT }}"
        gh release create v$(date +%Y%m%d%H%M%S) target/TemplatePlugin-1.jar --title "Release $(date +%Y%m%d%H%M%S)" --repo ${{ github.repository }} --notes "Automated release"
